# Generated by Django 5.0.3 on 2024-03-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.IntegerField(unique=True)),
                ('e_name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('sal', models.IntegerField()),
            ],
        ),
    ]
